### PR TITLE
tr_tr.json Turkish Localization

### PR DESCRIPTION
**Pull request by RuyaSavascisi**

### CODE REVIEW

**Review by Leclowndu93150 — APPROVED** [review]

**Comment by Leclowndu93150** [comment]
can it wait for next update ?

**Comment by RuyaSavascisi** [comment]
yeah, no problem with that

**Comment by RuyaSavascisi** [comment]
just sending little reminder message :)

**Comment by Leclowndu93150** [comment]
> just sending little reminder message :)

i did post it

**Comment by Leclowndu93150** [comment]
I DIDNT?

**Pull request merged**
